### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by matt-matt1** [victorballester7/title-bing-wallpaper#1]
> lsb_release -a                                                                                                              ✔  13:18:45 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

KDE Plasma Version 5.24.7

Installed then in KDE I right click and select Add Widget "Title Bing Wallpaper" appears.  Each time that I click on it, the top-left number increments but nothing happens. Then I close the Add Widget box and there's no difference on the desktop.  So I try another method instead, this time I drag it's icon onto the panel and a only blank space appears - without a name and no hover text.  Even in Enter Edit Mode, I choose Configure... on the blank and nothing appears.

What's going on?

**Comment by victorballester7** [comment]
Hi @matt-matt1 !!! Actually it's updated for KDE Plasma 6, so maybe this is the problem. Can you try to clone the repository on [this](https://github.com/victorballester7/title-bing-wallpaper/commit/f2d759618c4f7ae955b25422b7ac5b5d0124b52d) commit and see if you still get the error. That one should work for Plasma 5.
Thanks!

**Comment by matt-matt1** [comment]
Same as before.  But I don't see any difference in the URL (https://...), so I not sure I getting that commit.  (I've only used git clone and on own projects used git init, push and --set remote.  Is there another git command for this?)  So you think that it may not be compatible with v5.x plasma?

**Comment by victorballester7** [comment]
Try doing

```
git checkout f2d759618c4f7ae955b25422b7ac5b5d0124b52d
```

inside the local folder in your computer. This should update the code to the commit where the version for Plasma 5 was perfectly working. And answering you last question, yes, absolutely. They changed the way how qml files are handled in Plasma 6 (if I remember well) and so I had to do some small updates on the code.

**Comment by matt-matt1** [comment]
Thanks

**Comment by victorballester7** [comment]
It worked?

**Comment by victorballester7** [comment]
Ok, I close this issue since seems it's been solved. :)
